import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cn } from "@/lib/utils"
import { config } from "./../../config";

import "@/styles/globals.css";
import "@/styles/index.css";
// import "./globals.css";
import { cookieToInitialState } from "@account-kit/core";
import { headers } from "next/headers";
import { Providers } from "./providers";

const fontSans = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
})

 
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const initialState = cookieToInitialState(
    config,
    headers().get("cookie") ?? undefined
  );


  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <Providers initialState={initialState}>
        <main className="dark">
          {children}
        </main>
        </Providers>
      </body>
    </html>
  );
}
